# Generated by Django 4.0.5 on 2022-07-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teste_app', '0002_alter_post_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
